/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package ru.cwt.asn1.ericsson.sgw_r9;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class CreditRequestStatus extends BerEnum {

	private static final long serialVersionUID = 1L;

	public CreditRequestStatus() {
	}

	public CreditRequestStatus(byte[] code) {
		super(code);
	}

	public CreditRequestStatus(BigInteger value) {
		super(value);
	}

	public CreditRequestStatus(long value) {
		super(value);
	}

}
